package framework;

import graph.Vertex;
import javax.swing.ButtonGroup;

/**
 *
 * @author andrew
 */
public class MySolvePanel extends javax.swing.JPanel {

    /**
     * Creates new form MySolvePanel
     * @param currentProblem
     */
    public MySolvePanel(Problem currentProblem, State reset) {
        problem = currentProblem;
        resetState = reset;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
                         
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        SolvePanel = new javax.swing.JPanel();
        solveButton = new javax.swing.JButton();
        nextMoveButton = new javax.swing.JButton();
        allMovesButton = new javax.swing.JButton();
        statsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        solLengthStat = new javax.swing.JLabel();
        numDEQUEStat = new javax.swing.JLabel();
        maxSizeStat = new javax.swing.JLabel();
        radioButtonPanel = new javax.swing.JPanel();
        depthSearch = new javax.swing.JRadioButton();
        breadthSearch = new javax.swing.JRadioButton();

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        solveButton.setText("Solve");
        solveButton.setName("solveButton"); // NOI18N
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        nextMoveButton.setText("SHOW NEXT MOVE");
        nextMoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMoveButtonActionPerformed(evt);
            }
        });

        allMovesButton.setText("SHOW ALL MOVES");
        allMovesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allMovesButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Solution Length:");

        jLabel2.setText("Num of DEQUE Ops:");

        jLabel3.setText("Max DEQUE Size:");

        solLengthStat.setText("1");

        numDEQUEStat.setText("2");

        maxSizeStat.setText("3");

        javax.swing.GroupLayout statsPanelLayout = new javax.swing.GroupLayout(statsPanel);
        statsPanel.setLayout(statsPanelLayout);
        statsPanelLayout.setHorizontalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(maxSizeStat))
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(solLengthStat)
                            .addComponent(numDEQUEStat))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        statsPanelLayout.setVerticalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solLengthStat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numDEQUEStat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maxSizeStat))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        depthSearch.setText("Depth-First");
        depthSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depthSearchActionPerformed(evt);
            }
        });

        breadthSearch.setText("Breadth-First");
        breadthSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breadthSearchActionPerformed(evt);
            }
        });
        
        ButtonGroup group = new ButtonGroup();
        group.add(depthSearch);
        group.add(breadthSearch);

        javax.swing.GroupLayout radioButtonPanelLayout = new javax.swing.GroupLayout(radioButtonPanel);
        radioButtonPanel.setLayout(radioButtonPanelLayout);
        radioButtonPanelLayout.setHorizontalGroup(
            radioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(breadthSearch)
                    .addComponent(depthSearch))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        radioButtonPanelLayout.setVerticalGroup(
            radioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(depthSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breadthSearch)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout SolvePanelLayout = new javax.swing.GroupLayout(SolvePanel);
        SolvePanel.setLayout(SolvePanelLayout);
        SolvePanelLayout.setHorizontalGroup(
            SolvePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolvePanelLayout.createSequentialGroup()
                .addGroup(SolvePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolvePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(solveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SolvePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(SolvePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolvePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SolvePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextMoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allMovesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SolvePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(statsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        SolvePanelLayout.setVerticalGroup(
            SolvePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolvePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SolvePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SolvePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolvePanelLayout.createSequentialGroup()
                        .addComponent(nextMoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allMovesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(solveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SolvePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SolvePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }                      

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        if(depthSearch.isSelected())
            problem.breadthFirstSearch((Vertex) problem.getCurrentState());
        else
            problem.depthFirstSearch((Vertex) problem.getCurrentState());
        
        solLengthStat.setText(problem.getQueueSize()+"");
        numDEQUEStat.setText(problem.getQueueOps()+"");
        maxSizeStat.setText(problem.getMaxQueueSize()+"");
        
    }                                           

    private void nextMoveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void allMovesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void depthSearchActionPerformed(java.awt.event.ActionEvent evt) {                                            
        if(breadthSearch.isSelected() == true){
            breadthSearch.setSelected(false);
        }
    }                                           

    private void breadthSearchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(depthSearch.isSelected() == true){
            depthSearch.setSelected(false);
        }
    }                                             


    //variables
    private javax.swing.JPanel SolvePanel;
    private javax.swing.JButton allMovesButton;
    private javax.swing.JRadioButton breadthSearch;
    private javax.swing.JRadioButton depthSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel maxSizeStat;
    private javax.swing.JButton nextMoveButton;
    private javax.swing.JLabel numDEQUEStat;
    private javax.swing.JPanel radioButtonPanel;
    private javax.swing.JLabel solLengthStat;
    private javax.swing.JButton solveButton;
    private javax.swing.JPanel statsPanel;
    private Problem problem;
    private State resetState;
                
}
